import { ActivityLogActions, type ActivityLogAction } from "@/features/activity-logs/interfaces/activity-logs.interfaces";

export const ActivityLogActionFilterOptions: { id: ActivityLogAction | "all"; label: string }[] = [
  { id: "all", label: "All activity" },
  { id: ActivityLogActions.USER_REGISTERED, label: "Registered" },
  { id: ActivityLogActions.USER_LOGGED_IN, label: "Logged in" },
  { id: ActivityLogActions.USER_PROFILE_UPDATED, label: "Updated profile" },
  { id: ActivityLogActions.PASSWORD_CHANGED, label: "Changed password" },
  { id: ActivityLogActions.PASSWORD_RESET_COMPLETED, label: "Reset password" },
  { id: ActivityLogActions.ORGANISATION_CREATED, label: "Created organisation" },
  { id: ActivityLogActions.ORGANISATION_UPDATED, label: "Updated organisation" },
  { id: ActivityLogActions.ORGANISATION_DELETED, label: "Deleted organisation" },
  { id: ActivityLogActions.MEMBER_ADDED, label: "Added member" },
  { id: ActivityLogActions.MEMBER_INVITED, label: "Invited member" },
  { id: ActivityLogActions.MEMBER_INVITATION_RESENT, label: "Resent invitation" },
  { id: ActivityLogActions.MEMBER_INVITATION_ACCEPTED, label: "Accepted invitation" },
  { id: ActivityLogActions.MEMBER_ROLE_UPDATED, label: "Changed member role" },
  { id: ActivityLogActions.MEMBER_REMOVED, label: "Removed member" },
  { id: ActivityLogActions.DOCUMENT_UPLOADED, label: "Uploaded document" },
  { id: ActivityLogActions.DOCUMENT_UPDATED, label: "Updated document" },
  { id: ActivityLogActions.DOCUMENT_DELETED, label: "Deleted document" },
  { id: ActivityLogActions.STYLE_PROFILE_CREATED, label: "Created style profile" },
  { id: ActivityLogActions.STYLE_PROFILE_UPDATED, label: "Updated style profile" },
  { id: ActivityLogActions.STYLE_PROFILE_DELETED, label: "Deleted style profile" },
  { id: ActivityLogActions.STYLE_PROFILE_ANALYZED, label: "Analyzed style profile" },
  { id: ActivityLogActions.PROJECT_CREATED, label: "Created project" },
  { id: ActivityLogActions.PROJECT_UPDATED, label: "Updated project" },
  { id: ActivityLogActions.PROJECT_DELETED, label: "Deleted project" },
  { id: ActivityLogActions.PROJECT_STYLE_PROFILE_ATTACHED, label: "Attached style profile to project" },
  { id: ActivityLogActions.PROJECT_STYLE_PROFILE_DETACHED, label: "Detached style profile from project" },
  { id: ActivityLogActions.PROJECT_RSS_FEED_ATTACHED, label: "Attached RSS feed to project" },
  { id: ActivityLogActions.PROJECT_RSS_FEED_DETACHED, label: "Detached RSS feed from project" },
  { id: ActivityLogActions.RSS_FEED_CREATED, label: "Added RSS feed" },
  { id: ActivityLogActions.RSS_FEED_UPDATED, label: "Updated RSS feed" },
  { id: ActivityLogActions.RSS_FEED_DELETED, label: "Deleted RSS feed" },
  { id: ActivityLogActions.RSS_FEED_ITEMS_FETCHED, label: "Fetched RSS feed items" },
  { id: ActivityLogActions.AUTOMATION_CREATED, label: "Created automation" },
  { id: ActivityLogActions.AUTOMATION_UPDATED, label: "Updated automation" },
  { id: ActivityLogActions.AUTOMATION_DELETED, label: "Deleted automation" },
  { id: ActivityLogActions.AUTOMATION_RAN, label: "Automation ran" },
  { id: ActivityLogActions.GENERATION_RUN_CREATED, label: "Generated posts" },
  { id: ActivityLogActions.POST_CREATED, label: "Created post" },
  { id: ActivityLogActions.POST_UPDATED, label: "Updated post" },
  { id: ActivityLogActions.POST_DELETED, label: "Deleted post" },
  { id: ActivityLogActions.POST_SCHEDULED, label: "Scheduled post" },
  { id: ActivityLogActions.POST_PUBLISHED, label: "Published post" },
  { id: ActivityLogActions.POST_PUBLISH_FAILED, label: "Post failed to publish" },
  { id: ActivityLogActions.POST_REPURPOSED, label: "Repurposed post" },
  { id: ActivityLogActions.POST_ATTACHMENT_ADDED, label: "Added post attachment" },
  { id: ActivityLogActions.POST_ATTACHMENT_REMOVED, label: "Removed post attachment" },
  { id: ActivityLogActions.INTEGRATION_CONNECTED, label: "Connected integration" },
  { id: ActivityLogActions.INTEGRATION_UPDATED, label: "Updated integration" },
  { id: ActivityLogActions.INTEGRATION_REMOVED, label: "Disconnected integration" },
];

export function getActivityLogActionLabel(action: ActivityLogAction | string): string {
  return ActivityLogActionFilterOptions.find((option) => option.id === action)?.label ?? action;
}
