-- CreateEnum
CREATE TYPE "ActivityLogAction" AS ENUM ('USER_REGISTERED', 'USER_LOGGED_IN', 'USER_PROFILE_UPDATED', 'PASSWORD_CHANGED', 'PASSWORD_RESET_COMPLETED', 'ORGANISATION_CREATED', 'ORGANISATION_UPDATED', 'ORGANISATION_DELETED', 'MEMBER_ADDED', 'MEMBER_INVITED', 'MEMBER_INVITATION_RESENT', 'MEMBER_INVITATION_ACCEPTED', 'MEMBER_ROLE_UPDATED', 'MEMBER_REMOVED', 'DOCUMENT_UPLOADED', 'DOCUMENT_UPDATED', 'DOCUMENT_DELETED', 'STYLE_PROFILE_CREATED', 'STYLE_PROFILE_UPDATED', 'STYLE_PROFILE_DELETED', 'STYLE_PROFILE_ANALYZED', 'PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_DELETED', 'PROJECT_STYLE_PROFILE_ATTACHED', 'PROJECT_STYLE_PROFILE_DETACHED', 'PROJECT_RSS_FEED_ATTACHED', 'PROJECT_RSS_FEED_DETACHED', 'RSS_FEED_CREATED', 'RSS_FEED_UPDATED', 'RSS_FEED_DELETED', 'RSS_FEED_ITEMS_FETCHED', 'AUTOMATION_CREATED', 'AUTOMATION_UPDATED', 'AUTOMATION_DELETED', 'AUTOMATION_RAN', 'GENERATION_RUN_CREATED', 'POST_CREATED', 'POST_UPDATED', 'POST_DELETED', 'POST_SCHEDULED', 'POST_PUBLISHED', 'POST_PUBLISH_FAILED', 'POST_REPURPOSED', 'POST_ATTACHMENT_ADDED', 'POST_ATTACHMENT_REMOVED', 'POST_CHANNEL_ADDED', 'POST_CHANNEL_REMOVED', 'CHANNEL_CONNECTION_CREATED', 'CHANNEL_CONNECTION_UPDATED', 'CHANNEL_CONNECTION_REMOVED');

-- CreateEnum
CREATE TYPE "ActivityLogEntityType" AS ENUM ('USER', 'ORGANISATION', 'ORGANISATION_MEMBER', 'DOCUMENT', 'STYLE_PROFILE', 'PROJECT', 'RSS_FEED', 'AUTOMATION', 'GENERATION_RUN', 'POST', 'SOCIAL_CHANNEL_CONNECTION');

-- CreateTable
CREATE TABLE "activity_logs" (
    "id" TEXT NOT NULL,
    "organisation_id" TEXT,
    "user_id" TEXT,
    "action" "ActivityLogAction" NOT NULL,
    "entity_type" "ActivityLogEntityType",
    "entity_id" TEXT,
    "description" TEXT NOT NULL,
    "metadata" JSONB,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "activity_logs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "activity_logs_organisation_id_created_at_idx" ON "activity_logs"("organisation_id", "created_at");

-- CreateIndex
CREATE INDEX "activity_logs_user_id_idx" ON "activity_logs"("user_id");

-- CreateIndex
CREATE INDEX "activity_logs_action_idx" ON "activity_logs"("action");

-- AddForeignKey
ALTER TABLE "activity_logs" ADD CONSTRAINT "activity_logs_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "activity_logs" ADD CONSTRAINT "activity_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
