export const ErrorCodes = {
    Bookings: {
        BOOKING_ALREADY_EXISTS: 'BOOKING_ALREADY_EXISTS',
        NO_AVAILABLE_SLOTS: 'NO_AVAILABLE_SLOTS',
    },
    CreditsUsage: {
        INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
    },
    Users: {
        EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
        INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
    },
    Organisations: {
        SLUG_ALREADY_IN_USE: 'SLUG_ALREADY_IN_USE',
        NOT_A_MEMBER: 'NOT_A_MEMBER',
        LAST_OWNER: 'LAST_OWNER',
        MEMBER_ALREADY_EXISTS: 'MEMBER_ALREADY_EXISTS',
    },
    Posts: {
        INVALID_OWNER_CONTEXT: 'INVALID_OWNER_CONTEXT',
        INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
        BLOG_FIELDS_REQUIRED: 'BLOG_FIELDS_REQUIRED',
        NO_CHANNELS_TO_PUBLISH: 'NO_CHANNELS_TO_PUBLISH',
    },
    SocialChannels: {
        CHANNEL_ALREADY_CONNECTED: 'CHANNEL_ALREADY_CONNECTED',
        CHANNEL_NOT_CONNECTED: 'CHANNEL_NOT_CONNECTED',
        PUBLISH_FAILED: 'PUBLISH_FAILED',
    },
    Automations: {
        INVALID_SCHEDULE: 'INVALID_SCHEDULE',
    },
}
