import type { PaginationQuery } from "@/interfaces/pagination.interfaces";

export const ActivityLogActions = {
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGGED_IN: "USER_LOGGED_IN",
  USER_PROFILE_UPDATED: "USER_PROFILE_UPDATED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  ORGANISATION_CREATED: "ORGANISATION_CREATED",
  ORGANISATION_UPDATED: "ORGANISATION_UPDATED",
  ORGANISATION_DELETED: "ORGANISATION_DELETED",
  MEMBER_ADDED: "MEMBER_ADDED",
  MEMBER_INVITED: "MEMBER_INVITED",
  MEMBER_INVITATION_RESENT: "MEMBER_INVITATION_RESENT",
  MEMBER_INVITATION_ACCEPTED: "MEMBER_INVITATION_ACCEPTED",
  MEMBER_ROLE_UPDATED: "MEMBER_ROLE_UPDATED",
  MEMBER_REMOVED: "MEMBER_REMOVED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  DOCUMENT_UPDATED: "DOCUMENT_UPDATED",
  DOCUMENT_DELETED: "DOCUMENT_DELETED",
  STYLE_PROFILE_CREATED: "STYLE_PROFILE_CREATED",
  STYLE_PROFILE_UPDATED: "STYLE_PROFILE_UPDATED",
  STYLE_PROFILE_DELETED: "STYLE_PROFILE_DELETED",
  STYLE_PROFILE_ANALYZED: "STYLE_PROFILE_ANALYZED",
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_DELETED: "PROJECT_DELETED",
  PROJECT_STYLE_PROFILE_ATTACHED: "PROJECT_STYLE_PROFILE_ATTACHED",
  PROJECT_STYLE_PROFILE_DETACHED: "PROJECT_STYLE_PROFILE_DETACHED",
  PROJECT_RSS_FEED_ATTACHED: "PROJECT_RSS_FEED_ATTACHED",
  PROJECT_RSS_FEED_DETACHED: "PROJECT_RSS_FEED_DETACHED",
  RSS_FEED_CREATED: "RSS_FEED_CREATED",
  RSS_FEED_UPDATED: "RSS_FEED_UPDATED",
  RSS_FEED_DELETED: "RSS_FEED_DELETED",
  RSS_FEED_ITEMS_FETCHED: "RSS_FEED_ITEMS_FETCHED",
  AUTOMATION_CREATED: "AUTOMATION_CREATED",
  AUTOMATION_UPDATED: "AUTOMATION_UPDATED",
  AUTOMATION_DELETED: "AUTOMATION_DELETED",
  AUTOMATION_RAN: "AUTOMATION_RAN",
  GENERATION_RUN_CREATED: "GENERATION_RUN_CREATED",
  POST_CREATED: "POST_CREATED",
  POST_UPDATED: "POST_UPDATED",
  POST_DELETED: "POST_DELETED",
  POST_SCHEDULED: "POST_SCHEDULED",
  POST_PUBLISHED: "POST_PUBLISHED",
  POST_PUBLISH_FAILED: "POST_PUBLISH_FAILED",
  POST_REPURPOSED: "POST_REPURPOSED",
  POST_ATTACHMENT_ADDED: "POST_ATTACHMENT_ADDED",
  POST_ATTACHMENT_REMOVED: "POST_ATTACHMENT_REMOVED",
  POST_CHANNEL_ADDED: "POST_CHANNEL_ADDED",
  POST_CHANNEL_REMOVED: "POST_CHANNEL_REMOVED",
  CHANNEL_CONNECTION_CREATED: "CHANNEL_CONNECTION_CREATED",
  CHANNEL_CONNECTION_UPDATED: "CHANNEL_CONNECTION_UPDATED",
  CHANNEL_CONNECTION_REMOVED: "CHANNEL_CONNECTION_REMOVED",
} as const;
export type ActivityLogAction = (typeof ActivityLogActions)[keyof typeof ActivityLogActions];

export const ActivityLogEntityTypes = {
  USER: "USER",
  ORGANISATION: "ORGANISATION",
  ORGANISATION_MEMBER: "ORGANISATION_MEMBER",
  DOCUMENT: "DOCUMENT",
  STYLE_PROFILE: "STYLE_PROFILE",
  PROJECT: "PROJECT",
  RSS_FEED: "RSS_FEED",
  AUTOMATION: "AUTOMATION",
  GENERATION_RUN: "GENERATION_RUN",
  POST: "POST",
  SOCIAL_CHANNEL_CONNECTION: "SOCIAL_CHANNEL_CONNECTION",
} as const;
export type ActivityLogEntityType = (typeof ActivityLogEntityTypes)[keyof typeof ActivityLogEntityTypes];

export interface ActivityLog {
  id: string;
  organisation_id: string | null;
  user: { id: string; name: string; email: string } | null;
  action: ActivityLogAction;
  entity_type: ActivityLogEntityType | null;
  entity_id: string | null;
  description: string;
  metadata?: Record<string, unknown> | null;
  created_at: string;
}

export interface ActivityLogsQueryType extends PaginationQuery {
  action?: ActivityLogAction;
  entity_type?: ActivityLogEntityType;
  user_id?: string;
  from?: string;
  to?: string;
}
